import type { CoachFeedback, StudentAthlete } from "@/types";

export const students: StudentAthlete[] = [
  {
    id: "s1",
    name: "Ethan Park",
    age: 14,
    level: "HS Freshman",
    position: "OF / RHH",
    parentName: "Jennifer Park",
    location: "Los Angeles, CA",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Ethan",
    lessonsCompleted: 12,
    nextLesson: "2026-08-02",
    focusAreas: ["バッティング", "走塁"],
    aiSummary:
      "Bat speed +4 mph over 6 weeks. Attack angle still shallow on outside pitches — prioritize path drills.",
    strengths: ["Load timing", "Lower-half drive", "Competitive at-bats"],
    improvements: ["Outside pitch attack angle", "Early hip clear", "Two-strike approach"],
    metrics: {
      batSpeed: 68,
      attackAngle: 6,
      hipRotation: 72,
      exitVelo: 82,
      consistency: 78,
    },
    history: [
      { date: "05-01", batSpeed: 64, attackAngle: 3, hipRotation: 65, exitVelo: 76 },
      { date: "05-15", batSpeed: 65, attackAngle: 4, hipRotation: 67, exitVelo: 78 },
      { date: "06-01", batSpeed: 66, attackAngle: 5, hipRotation: 69, exitVelo: 79 },
      { date: "06-15", batSpeed: 67, attackAngle: 5, hipRotation: 70, exitVelo: 81 },
      { date: "07-01", batSpeed: 67, attackAngle: 6, hipRotation: 71, exitVelo: 81 },
      { date: "07-20", batSpeed: 68, attackAngle: 6, hipRotation: 72, exitVelo: 82 },
    ],
    lastSessionNote: "Worked on toe-tap load and middle-away barrel path.",
    lessonLog: [
      { id: "l1a", date: "2026-07-20", focus: "Barrel path", notes: "Toe-tap load · middle-away", durationMin: 60 },
      { id: "l1b", date: "2026-07-13", focus: "Lower half", notes: "Drive drills · video review", durationMin: 60 },
      { id: "l1c", date: "2026-07-06", focus: "Two-strike", notes: "Shorter swing constraints", durationMin: 45 },
    ],
  },
  {
    id: "s2",
    name: "Sofia Reyes",
    age: 16,
    level: "HS Junior",
    position: "P / RHP",
    parentName: "Carlos Reyes",
    location: "Orange County, CA",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia",
    lessonsCompleted: 8,
    nextLesson: "2026-07-31",
    focusAreas: ["ピッチング", "フィジカル"],
    aiSummary:
      "Arm slot consistency improved. Peak velo 64 mph. Focus next block on hip-shoulder separation.",
    strengths: ["Command of FB", "Work ethic", "Recovery habits"],
    improvements: ["Hip-shoulder separation", "Glove-side finish", "Changeup arm speed"],
    metrics: {
      batSpeed: 0,
      attackAngle: 0,
      hipRotation: 68,
      exitVelo: 64,
      consistency: 84,
    },
    history: [
      { date: "05-01", batSpeed: 0, attackAngle: 0, hipRotation: 60, exitVelo: 60 },
      { date: "05-15", batSpeed: 0, attackAngle: 0, hipRotation: 62, exitVelo: 61 },
      { date: "06-01", batSpeed: 0, attackAngle: 0, hipRotation: 64, exitVelo: 62 },
      { date: "06-15", batSpeed: 0, attackAngle: 0, hipRotation: 65, exitVelo: 63 },
      { date: "07-01", batSpeed: 0, attackAngle: 0, hipRotation: 67, exitVelo: 63 },
      { date: "07-20", batSpeed: 0, attackAngle: 0, hipRotation: 68, exitVelo: 64 },
    ],
    lastSessionNote: "Video review of glove-side pull and front-side bracing.",
    lessonLog: [
      { id: "l2a", date: "2026-07-22", focus: "Hip-shoulder sep", notes: "Light FB command · video", durationMin: 60 },
      { id: "l2b", date: "2026-07-15", focus: "Arm slot", notes: "Consistency block", durationMin: 50 },
      { id: "l2c", date: "2026-07-08", focus: "Changeup", notes: "Arm speed matching", durationMin: 45 },
    ],
  },
  {
    id: "s3",
    name: "Kenji Nakamura",
    age: 11,
    level: "Youth 11U",
    position: "SS / RHH",
    parentName: "Yuki Nakamura",
    location: "San Diego, CA",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Kenji",
    lessonsCompleted: 5,
    nextLesson: "2026-08-03",
    focusAreas: ["守備", "バッティング"],
    aiSummary:
      "Early footwork improved on ground balls. Swing is long — shorten path with tee constraints.",
    strengths: ["Hands soft", "Game IQ", "Coachable"],
    improvements: ["Swing length", "First-step quickness", "Throwing accuracy"],
    metrics: {
      batSpeed: 52,
      attackAngle: 8,
      hipRotation: 55,
      exitVelo: 58,
      consistency: 65,
    },
    history: [
      { date: "05-01", batSpeed: 48, attackAngle: 10, hipRotation: 50, exitVelo: 52 },
      { date: "05-15", batSpeed: 49, attackAngle: 9, hipRotation: 51, exitVelo: 54 },
      { date: "06-01", batSpeed: 50, attackAngle: 9, hipRotation: 52, exitVelo: 55 },
      { date: "06-15", batSpeed: 51, attackAngle: 8, hipRotation: 53, exitVelo: 56 },
      { date: "07-01", batSpeed: 51, attackAngle: 8, hipRotation: 54, exitVelo: 57 },
      { date: "07-20", batSpeed: 52, attackAngle: 8, hipRotation: 55, exitVelo: 58 },
    ],
    lastSessionNote: "Short-bat tee work + funnel drills for backhand.",
    lessonLog: [
      { id: "l3a", date: "2026-07-18", focus: "Defense", notes: "Funnel + backhand", durationMin: 45 },
      { id: "l3b", date: "2026-07-11", focus: "Swing length", notes: "Short-bat tee", durationMin: 45 },
    ],
  },
  {
    id: "s4",
    name: "Maya Chen",
    age: 17,
    level: "HS Senior",
    position: "C / Switch",
    location: "San Francisco Bay Area, CA",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Maya",
    lessonsCompleted: 15,
    nextLesson: "2026-08-05",
    focusAreas: ["キャッチャー", "メンタル"],
    aiSummary:
      "Pop time average 2.05s. Framing gains noted. Mental routine before 2-strike counts is sticky.",
    strengths: ["Receiving", "Leadership", "Block technique"],
    improvements: ["Transfer speed", "LH swing path", "Breathing under pressure"],
    metrics: {
      batSpeed: 62,
      attackAngle: 9,
      hipRotation: 70,
      exitVelo: 74,
      consistency: 88,
    },
    history: [
      { date: "05-01", batSpeed: 58, attackAngle: 7, hipRotation: 64, exitVelo: 70 },
      { date: "05-15", batSpeed: 59, attackAngle: 8, hipRotation: 65, exitVelo: 71 },
      { date: "06-01", batSpeed: 60, attackAngle: 8, hipRotation: 67, exitVelo: 72 },
      { date: "06-15", batSpeed: 61, attackAngle: 9, hipRotation: 68, exitVelo: 73 },
      { date: "07-01", batSpeed: 61, attackAngle: 9, hipRotation: 69, exitVelo: 73 },
      { date: "07-20", batSpeed: 62, attackAngle: 9, hipRotation: 70, exitVelo: 74 },
    ],
    lastSessionNote: "Transfer drills + lefty side soft-toss.",
    lessonLog: [
      { id: "l4a", date: "2026-07-21", focus: "Transfer", notes: "Pop-time block", durationMin: 60 },
      { id: "l4b", date: "2026-07-14", focus: "LH swing", notes: "Soft-toss path", durationMin: 55 },
      { id: "l4c", date: "2026-07-07", focus: "Framing", notes: "Glove quiet work", durationMin: 50 },
    ],
  },
];

export const seedFeedback: CoachFeedback[] = [
  {
    id: "f1",
    studentId: "s1",
    studentName: "Ethan Park",
    subject: "Session recap — path on away pitches",
    body: "Great session today. Keep the barrel above the ball on the outside pitch. I attached your AI swing trends — bat speed is climbing.",
    createdAt: "2026-07-20T18:00:00",
    aiAttached: true,
  },
  {
    id: "f2",
    studentId: "s2",
    studentName: "Sofia Reyes",
    subject: "Between-starts plan",
    body: "Focus on hip-shoulder separation drills Mon/Wed. Keep FB command work light before your Friday start.",
    createdAt: "2026-07-22T10:30:00",
    aiAttached: false,
  },
];

export function getStudentById(id: string) {
  return students.find((s) => s.id === id);
}
