import type {
  Booking,
  CoachProfile,
  Localized,
  Message,
  MessageThread,
  Review,
  TimeSlot,
} from "@/types";

export const SPORTS = ["baseball", "softball", "basketball", "soccer"] as const;

export const SPECIALTIES = [
  "hitting",
  "pitching",
  "defense",
  "baserunning",
  "catcher",
  "physical",
  "mental",
  "scouting",
] as const;

/** California launch metros */
export const LOCATIONS = [
  "Los Angeles",
  "Orange County",
  "San Diego",
  "San Francisco Bay Area",
  "Sacramento",
  "Inland Empire",
  "Central Valley",
] as const;

/**
 * High-demand coaching languages for the CA market
 * (English / Spanish core, plus strong Asian diaspora demand).
 */
export const LANGUAGES = [
  "english",
  "spanish",
  "japanese",
  "mandarin",
  "cantonese",
  "korean",
  "portuguese",
  "tagalog",
] as const;

const L = (en: string, ja: string, es: string): Localized => ({ en, ja, es });

export const coaches: CoachProfile[] = [
  {
    id: "c1",
    userId: "u-coach-1",
    name: "Shota Tanaka",
    email: "tanaka@athlink.app",
    sport: "baseball",
    specialties: ["hitting", "baserunning"],
    bio: L(
      "Former pro baseball player. Specializes in swing building for youth through high school — blending motion analysis with feel that works on the field.",
      "元プロ野球選手。少年〜高校生のスイング作りが得意。科学的な動作分析と、現場で使える感覚の両立を大切にしています。",
      "Exjugador profesional. Especialista en construir swings desde juveniles hasta preparatoria — combina análisis de movimiento con sensaciones útiles en el campo.",
    ),
    location: "Los Angeles, CA",
    city: "Los Angeles",
    prefecture: "Los Angeles",
    experienceYears: 12,
    pricePerHour: 95,
    rating: 4.9,
    reviewCount: 48,
    verified: true,
    formats: ["in_person", "online"],
    avatarUrl: "/coaches/shota-tanaka.jpg",
    coverGradient: "from-sky-600 to-indigo-700",
    career: [
      L("Former NPB outfielder", "元NPB外野手", "Exjardinero de NPB"),
      L("8 years high school coaching", "高校野球コーチ経験8年", "8 años como coach de preparatoria"),
      L("USA Baseball certified coach", "USA Baseball認定コーチ", "Coach certificado por USA Baseball"),
    ],
    languages: ["japanese", "english"],
    availabilityNote: "Weeknights & Saturday mornings",
  },
  {
    id: "c2",
    userId: "u-coach-2",
    name: "Misaki Suzuki",
    email: "suzuki@athlink.app",
    sport: "baseball",
    specialties: ["pitching", "physical"],
    bio: L(
      "Women’s pro baseball alum. Pitching instruction focused on velocity gains and injury prevention — popular with female athletes and parents.",
      "女子プロ野球出身。球速アップとケガ予防にフォーカスしたピッチング指導。女性選手・保護者からも人気です。",
      "Exjugadora de béisbol profesional femenino. Pitching enfocado en velocidad y prevención de lesiones — popular entre atletas y padres.",
    ),
    location: "Orange County, CA",
    city: "Irvine",
    prefecture: "Orange County",
    experienceYears: 9,
    pricePerHour: 85,
    rating: 4.8,
    reviewCount: 36,
    verified: true,
    formats: ["in_person"],
    avatarUrl: "/coaches/misaki-suzuki.jpg",
    coverGradient: "from-rose-500 to-orange-500",
    career: [
      L("Former women’s pro pitcher", "元女子プロ野球投手", "Exlanzadora profesional femenina"),
      L("Licensed physical therapist", "理学療法士ライセンス", "Fisioterapeuta licenciada"),
      L("Youth academy instructor", "ユースアカデミー指導", "Instructora de academia juvenil"),
    ],
    languages: ["japanese", "english"],
    availabilityNote: "Weekends only",
  },
  {
    id: "c3",
    userId: "u-coach-3",
    name: "Ken Yamada",
    email: "yamada@athlink.app",
    sport: "baseball",
    specialties: ["defense", "catcher"],
    bio: L(
      "College baseball Final Four. Teaches catcher and infield defense from fundamentals through game decisions.",
      "大学野球で全国ベスト4。捕手・内野守備の基礎から、実戦での判断力まで丁寧に教えます。",
      "Final Four universitario. Enseña defensa de receptor e infield desde lo básico hasta decisiones de juego.",
    ),
    location: "San Diego, CA",
    city: "San Diego",
    prefecture: "San Diego",
    experienceYears: 7,
    pricePerHour: 70,
    rating: 4.7,
    reviewCount: 22,
    verified: true,
    formats: ["in_person", "online"],
    avatarUrl: "/coaches/ken-yamada.jpg",
    coverGradient: "from-emerald-600 to-teal-700",
    career: [
      L("College baseball Final Four", "大学野球全国ベスト4", "Final Four universitario"),
      L("Independent league coaching", "独立リーグコーチ経験", "Coach en liga independiente"),
      L("Youth club manager", "少年野球クラブ監督", "Manager de club juvenil"),
    ],
    languages: ["english", "japanese"],
    availabilityNote: "Weekday evenings",
  },
  {
    id: "c4",
    userId: "u-coach-4",
    name: "John Martinez",
    email: "john@athlink.app",
    sport: "baseball",
    specialties: ["hitting", "scouting"],
    bio: L(
      "MLB minor league experience. Bridges U.S. training methods with Japanese baseball culture. Lessons in English and Spanish.",
      "MLBマイナーリーグ経験。米国式トレーニングと日本の野球文化を橋渡し。英語・スペイン語レッスン対応。",
      "Experiencia en ligas menores de MLB. Une métodos de EE. UU. con la cultura del béisbol japonés. Clases en inglés y español.",
    ),
    location: "Los Angeles, CA",
    city: "Los Angeles",
    prefecture: "Los Angeles",
    experienceYears: 15,
    pricePerHour: 140,
    rating: 5.0,
    reviewCount: 19,
    verified: true,
    formats: ["in_person", "online"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=John",
    coverGradient: "from-blue-700 to-slate-800",
    career: [
      L("Former MLB minor leaguer", "元MLBマイナー", "Exjugador de ligas menores MLB"),
      L("USC baseball program instructor", "USC野球プログラム指導", "Instructor del programa USC"),
      L("Scout advisor", "スカウトアドバイザー", "Asesor de scouting"),
    ],
    languages: ["english", "spanish", "japanese"],
    availabilityNote: "Book 1 week ahead",
  },
  {
    id: "c5",
    userId: "u-coach-5",
    name: "Naoki Sato",
    email: "sato@athlink.app",
    sport: "baseball",
    specialties: ["mental", "hitting"],
    bio: L(
      "Sport psychology–credentialed coach. Helps athletes who get tight under pressure build mental toughness and game-day performance.",
      "スポーツ心理士資格を持つコーチ。緊張しやすい選手のメンタル強化と試合でのパフォーマンス向上を支援します。",
      "Coach con credencial en psicología del deporte. Ayuda a atletas que se tensan bajo presión a ganar firmeza mental y rendimiento.",
    ),
    location: "San Francisco Bay Area, CA",
    city: "San Jose",
    prefecture: "San Francisco Bay Area",
    experienceYears: 10,
    pricePerHour: 80,
    rating: 4.6,
    reviewCount: 31,
    verified: false,
    formats: ["online"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sato",
    coverGradient: "from-violet-600 to-purple-800",
    career: [
      L("Sport psychologist", "スポーツ心理士", "Psicólogo del deporte"),
      L("High school mental performance coach", "高校野球メンタルコーチ", "Coach mental de preparatoria"),
      L("Pro athlete support experience", "プロ選手サポート経験", "Experiencia con atletas pro"),
    ],
    languages: ["japanese", "english", "mandarin"],
    availabilityNote: "Online · evenings available",
  },
  {
    id: "c6",
    userId: "u-coach-6",
    name: "Ayumi Nakamura",
    email: "nakamura@athlink.app",
    sport: "softball",
    specialties: ["pitching", "defense"],
    bio: L(
      "Japan national softball experience. Windmill pitching from foundations through game application.",
      "ソフトボール日本代表経験。ウィンドミル投法の基礎から実戦までの一貫指導。",
      "Experiencia con la selección de softbol de Japón. Pitcheo windmill desde lo básico hasta el juego real.",
    ),
    location: "Sacramento, CA",
    city: "Sacramento",
    prefecture: "Sacramento",
    experienceYears: 11,
    pricePerHour: 90,
    rating: 4.9,
    reviewCount: 27,
    verified: true,
    formats: ["in_person", "online"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Nakamura",
    coverGradient: "from-amber-500 to-red-600",
    career: [
      L("Japan national softball", "ソフトボール日本代表", "Selección de softbol de Japón"),
      L("College softball head coach", "大学ソフトボール監督", "Head coach universitario de softbol"),
      L("Junior development coach", "ジュニア育成コーチ", "Coach de desarrollo junior"),
    ],
    languages: ["japanese", "english"],
    availabilityNote: "Weekends in-person · weekday online",
  },
  {
    id: "c7",
    userId: "u-coach-7",
    name: "Diego Alvarez",
    email: "diego@athlink.app",
    sport: "baseball",
    specialties: ["physical", "baserunning"],
    bio: L(
      "Track background turned strength coach. Baseball-specific speed and power programs. Spanish available.",
      "元陸上部出身のストレングスコーチ。野球特化のスピード・パワー強化プログラムを提供。スペイン語対応。",
      "Fondo en atletismo, ahora coach de fuerza. Programas de velocidad y potencia para béisbol. Disponible en español.",
    ),
    location: "Inland Empire, CA",
    city: "Riverside",
    prefecture: "Inland Empire",
    experienceYears: 6,
    pricePerHour: 65,
    rating: 4.5,
    reviewCount: 14,
    verified: true,
    formats: ["in_person"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Diego",
    coverGradient: "from-lime-600 to-green-800",
    career: [
      L("NSCA-CSCS", "NSCA-CSCS", "NSCA-CSCS"),
      L("Pro S&C assistant", "プロ球団S&Cアシスタント", "Asistente de S&C profesional"),
      L("High school track coach", "高校陸上部コーチ", "Coach de atletismo en preparatoria"),
    ],
    languages: ["spanish", "english"],
    availabilityNote: "Weekday afternoons & Saturdays",
  },
  {
    id: "c8",
    userId: "u-coach-8",
    name: "Ren Takahashi",
    email: "takahashi@athlink.app",
    sport: "baseball",
    specialties: ["hitting", "defense", "scouting"],
    bio: L(
      "Koshien tournament experience. Pairs technical coaching with pathway advising for middle and high school athletes.",
      "甲子園出場経験あり。中学〜高校生の進路相談と技術指導をセットでサポートします。",
      "Experiencia en el torneo Koshien. Une coaching técnico con orientación de camino para secundaria y preparatoria.",
    ),
    location: "Central Valley, CA",
    city: "Fresno",
    prefecture: "Central Valley",
    experienceYears: 8,
    pricePerHour: 75,
    rating: 4.8,
    reviewCount: 41,
    verified: true,
    formats: ["in_person", "online"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Takahashi",
    coverGradient: "from-cyan-600 to-blue-800",
    career: [
      L("Koshien participant", "甲子園出場", "Participante de Koshien"),
      L("College baseball captain", "大学野球主将", "Capitán universitario"),
      L("Independent private coach", "独立系プライベートコーチ", "Coach privado independiente"),
    ],
    languages: ["japanese", "english", "korean"],
    availabilityNote: "Flexible by booking",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    coachId: "c1",
    authorName: "Parent · K",
    rating: 5,
    comment: L(
      "My son’s swing looked completely different in a month. Clear explanations and thoughtful parent feedback.",
      "息子のスイングが1ヶ月で見違えるほど変わりました。説明が分かりやすく、保護者にも丁寧にフィードバックしてくれます。",
      "El swing de mi hijo cambió por completo en un mes. Explicaciones claras y buen feedback para padres.",
    ),
    date: "2026-06-12",
    athleteLevel: "Grade 5",
  },
  {
    id: "r2",
    coachId: "c1",
    authorName: "Athlete · Y",
    rating: 5,
    comment: L(
      "Even online, the video breakdown is detailed — I get points I can try at the next practice.",
      "オンラインでも動画解析が丁寧で、次の練習ですぐ試せるポイントがもらえます。",
      "Aunque sea en línea, el análisis de video es detallado — salgo con puntos para la próxima práctica.",
    ),
    date: "2026-05-28",
    athleteLevel: "HS Sophomore",
  },
  {
    id: "r2b",
    coachId: "c1",
    authorName: "Parent · P",
    rating: 5,
    comment: L(
      "Coach Tanaka remembers what we worked on last time — my daughter feels seen every session.",
      "前回の内容を覚えていてくれる。娘が毎回「見てもらえてる」と言います。",
      "Coach Tanaka recuerda lo de la sesión anterior — mi hija siente que la ven en cada clase.",
    ),
    date: "2026-07-08",
    athleteLevel: "HS Freshman",
  },
  {
    id: "r2c",
    coachId: "c1",
    authorName: "Athlete · E",
    rating: 4,
    comment: L(
      "Tough but fair. The cage drills finally clicked after three weeks.",
      "厳しいけど納得できる。3週間でケージのドリルが体に入った。",
      "Exigente pero justo. Los drills de jaula por fin encajaron después de tres semanas.",
    ),
    date: "2026-06-22",
    athleteLevel: "Youth 12U",
  },
  {
    id: "r2d",
    coachId: "c1",
    authorName: "Parent · R",
    rating: 5,
    comment: L(
      "Scheduling is easy and the post-lesson notes help us practice at home.",
      "予約がスムーズで、レッスン後のメモで家練習の指針がはっきりする。",
      "Reservar es fácil y las notas post-clase nos ayudan a practicar en casa.",
    ),
    date: "2026-07-15",
    athleteLevel: "Grade 6",
  },
  {
    id: "r3",
    coachId: "c2",
    authorName: "Athlete · A",
    rating: 5,
    comment: L(
      "My velocity went up. Learning injury-prevention care made me feel safer too.",
      "球速が上がりました。ケガ予防のケアも教えてもらえて安心です。",
      "Subí la velocidad. Aprender cuidados para prevenir lesiones también me dio tranquilidad.",
    ),
    date: "2026-06-01",
    athleteLevel: "8th grade",
  },
  {
    id: "r4",
    coachId: "c4",
    authorName: "Parent · M",
    rating: 5,
    comment: L(
      "He blends U.S. and Japanese practice ideas well — my son’s motivation jumped.",
      "アメリカの考え方と日本の練習をうまく組み合わせてくれて、息子のモチベーションが上がりました。",
      "Combina bien ideas de EE. UU. y Japón — la motivación de mi hijo subió.",
    ),
    date: "2026-04-18",
    athleteLevel: "HS Freshman",
  },
  {
    id: "r5",
    coachId: "c6",
    authorName: "Athlete · S",
    rating: 5,
    comment: L(
      "Fixed my windmill form from the ground up — control is much more consistent now.",
      "ウィンドミルのフォームを基礎から直してもらい、コントロールが安定しました。",
      "Corrigió mi forma windmill desde cero — el control ahora es mucho más estable.",
    ),
    date: "2026-05-05",
    athleteLevel: "HS Sophomore",
  },
  {
    id: "r6",
    coachId: "c8",
    authorName: "Parent · T",
    rating: 4,
    comment: L(
      "Pathway advising alongside skills work was reassuring. Technique keeps improving steadily.",
      "進路相談も一緒にしてくれて心強かったです。技術面も着実に伸びています。",
      "La orientación de camino junto al trabajo técnico fue un alivio. La técnica sigue mejorando.",
    ),
    date: "2026-06-20",
    athleteLevel: "8th grade",
  },
];

function buildSlots(): TimeSlot[] {
  const slots: TimeSlot[] = [];
  const times = [
    ["09:00", "10:00"],
    ["10:30", "11:30"],
    ["13:00", "14:00"],
    ["15:00", "16:00"],
    ["17:00", "18:00"],
    ["19:00", "20:00"],
  ];
  const start = new Date("2026-07-28T00:00:00");
  coaches.forEach((coach, ci) => {
    for (let d = 0; d < 14; d++) {
      const date = new Date(start);
      date.setDate(start.getDate() + d);
      const dateStr = date.toISOString().slice(0, 10);
      times.forEach(([startTime, endTime], ti) => {
        slots.push({
          id: `${coach.id}-${dateStr}-${startTime}`,
          coachId: coach.id,
          date: dateStr,
          startTime,
          endTime,
          available: (ci + d + ti) % 3 !== 0,
        });
      });
    }
  });
  return slots;
}

export const timeSlots = buildSlots();

export const demoBookings: Booking[] = [
  {
    id: "b1",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-1",
    athleteName: "Ethan Park",
    date: "2026-07-30",
    startTime: "17:00",
    endTime: "18:00",
    format: "in_person",
    packageType: "single",
    price: 95,
    status: "confirmed",
    note: "Please review batting form",
    createdAt: "2026-07-20T10:00:00",
  },
  {
    id: "b2",
    coachId: "c5",
    coachName: "Naoki Sato",
    athleteId: "u-athlete-1",
    athleteName: "Demo Athlete",
    date: "2026-08-02",
    startTime: "19:00",
    endTime: "20:00",
    format: "online",
    packageType: "single",
    price: 80,
    status: "pending",
    createdAt: "2026-07-25T14:30:00",
  },
  {
    id: "b3",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-2",
    athleteName: "Sofia Reyes",
    date: "2026-07-29",
    startTime: "16:00",
    endTime: "17:00",
    format: "in_person",
    packageType: "single",
    price: 95,
    status: "pending",
    note: "QR scan · pitching session",
    createdAt: "2026-07-28T09:00:00",
  },
  {
    id: "b4",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-3",
    athleteName: "Kenji Nakamura",
    date: "2026-07-31",
    startTime: "18:00",
    endTime: "19:00",
    format: "in_person",
    packageType: "pack",
    price: 428,
    status: "pending",
    createdAt: "2026-07-27T11:20:00",
  },
  {
    id: "b5",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-4",
    athleteName: "Maya Chen",
    date: "2026-08-01",
    startTime: "10:00",
    endTime: "11:00",
    format: "in_person",
    packageType: "single",
    price: 95,
    status: "confirmed",
    createdAt: "2026-07-26T16:00:00",
  },
  {
    id: "b6",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-2",
    athleteName: "Sofia Reyes",
    date: "2026-08-05",
    startTime: "17:00",
    endTime: "18:00",
    format: "online",
    packageType: "single",
    price: 95,
    status: "confirmed",
    createdAt: "2026-07-28T12:00:00",
  },
  {
    id: "b7",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-5",
    athleteName: "Liam Ortiz",
    date: "2026-08-08",
    startTime: "09:00",
    endTime: "10:00",
    format: "in_person",
    packageType: "single",
    price: 95,
    status: "pending",
    createdAt: "2026-07-29T08:00:00",
  },
];

export const messageThreads: MessageThread[] = [
  {
    id: "t1",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-1",
    athleteName: "you",
    lastMessage: L(
      "Please bring your swing video next time!",
      "次回はスイング動画を持ってきてください！",
      "¡Trae tu video de swing la próxima vez!",
    ),
    updatedAt: "2026-07-26T18:20:00",
    unread: 1,
  },
  {
    id: "t2",
    coachId: "c2",
    coachName: "Misaki Suzuki",
    athleteId: "u-athlete-1",
    athleteName: "you",
    lastMessage: L(
      "Thanks for booking a trial lesson.",
      "体験レッスンのご予約、ありがとうございます。",
      "Gracias por reservar la clase de prueba.",
    ),
    updatedAt: "2026-07-24T09:10:00",
    unread: 0,
  },
];

export const messages: Message[] = [
  {
    id: "m1",
    threadId: "t1",
    senderId: "u-athlete-1",
    senderName: "you",
    senderNameKey: "you",
    body: L(
      "Thanks again for last session, Coach Tanaka. Looking forward to the next one.",
      "田中コーチ、先日はありがとうございました。次回もよろしくお願いします。",
      "Gracias otra vez por la sesión, Coach Tanaka. Nos vemos en la próxima.",
    ),
    createdAt: "2026-07-26T17:50:00",
  },
  {
    id: "m2",
    threadId: "t1",
    senderId: "u-coach-1",
    senderName: "Shota Tanaka",
    body: L(
      "Likewise! Please bring your swing video next time!",
      "こちらこそ！次回はスイング動画を持ってきてください！",
      "¡Igualmente! Trae tu video de swing la próxima vez.",
    ),
    createdAt: "2026-07-26T18:20:00",
  },
  {
    id: "m3",
    threadId: "t2",
    senderId: "u-coach-2",
    senderName: "Misaki Suzuki",
    body: L(
      "Thanks for booking a trial lesson. Please wear something easy to move in.",
      "体験レッスンのご予約、ありがとうございます。当日は動きやすい服装でお越しください。",
      "Gracias por la clase de prueba. Ven con ropa cómoda para moverte.",
    ),
    createdAt: "2026-07-24T09:10:00",
  },
];

export function getCoachById(id: string) {
  return coaches.find((c) => c.id === id);
}

export function getReviewsByCoach(coachId: string) {
  return reviews.filter((r) => r.coachId === coachId);
}

export function getSlotsByCoach(coachId: string) {
  return timeSlots.filter((s) => s.coachId === coachId && s.available);
}
