import type {
  Booking,
  CoachProfile,
  Message,
  MessageThread,
  Review,
  TimeSlot,
} from "@/types";

export const SPORTS = ["野球", "ソフトボール", "バスケ", "サッカー"] as const;

export const SPECIALTIES = [
  "バッティング",
  "ピッチング",
  "守備",
  "走塁",
  "キャッチャー",
  "フィジカル",
  "メンタル",
  "スカウト対策",
] as const;

/** California launch metros */
export const LOCATIONS = [
  "Los Angeles",
  "Orange County",
  "San Diego",
  "San Francisco Bay Area",
  "Sacramento",
  "Inland Empire",
  "Central Valley",
] as const;

/**
 * High-demand coaching languages for the CA market
 * (English / Spanish core, plus strong Asian diaspora demand).
 */
export const LANGUAGES = [
  "English",
  "Spanish",
  "Japanese",
  "Mandarin",
  "Cantonese",
  "Korean",
  "Portuguese",
  "Tagalog",
] as const;

export const coaches: CoachProfile[] = [
  {
    id: "c1",
    userId: "u-coach-1",
    name: "Shota Tanaka",
    email: "tanaka@athlink.app",
    sport: "野球",
    specialties: ["バッティング", "走塁"],
    bio: "元プロ野球選手。少年〜高校生のスイング作りが得意。科学的な動作分析と、現場で使える感覚の両立を大切にしています。",
    location: "Los Angeles, CA",
    city: "Los Angeles",
    prefecture: "Los Angeles",
    experienceYears: 12,
    pricePerHour: 95,
    rating: 4.9,
    reviewCount: 48,
    verified: true,
    formats: ["in_person", "online"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Tanaka",
    coverGradient: "from-sky-600 to-indigo-700",
    career: ["元NPB外野手", "高校野球コーチ経験8年", "USA Baseball認定コーチ"],
    languages: ["Japanese", "English"],
    availabilityNote: "Weeknights & Saturday mornings",
  },
  {
    id: "c2",
    userId: "u-coach-2",
    name: "Misaki Suzuki",
    email: "suzuki@athlink.app",
    sport: "野球",
    specialties: ["ピッチング", "フィジカル"],
    bio: "女子プロ野球出身。球速アップとケガ予防にフォーカスしたピッチング指導。女性選手・保護者からも人気です。",
    location: "Orange County, CA",
    city: "Irvine",
    prefecture: "Orange County",
    experienceYears: 9,
    pricePerHour: 85,
    rating: 4.8,
    reviewCount: 36,
    verified: true,
    formats: ["in_person"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Suzuki",
    coverGradient: "from-rose-500 to-orange-500",
    career: ["元女子プロ野球投手", "理学療法士ライセンス", "ユースアカデミー指導"],
    languages: ["Japanese", "English"],
    availabilityNote: "Weekends only",
  },
  {
    id: "c3",
    userId: "u-coach-3",
    name: "Ken Yamada",
    email: "yamada@athlink.app",
    sport: "野球",
    specialties: ["守備", "キャッチャー"],
    bio: "大学野球で全国ベスト4。捕手・内野守備の基礎から、実戦での判断力まで丁寧に教えます。",
    location: "San Diego, CA",
    city: "San Diego",
    prefecture: "San Diego",
    experienceYears: 7,
    pricePerHour: 70,
    rating: 4.7,
    reviewCount: 22,
    verified: true,
    formats: ["in_person", "online"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Yamada",
    coverGradient: "from-emerald-600 to-teal-700",
    career: ["大学野球全国ベスト4", "独立リーグコーチ経験", "少年野球クラブ監督"],
    languages: ["English", "Japanese"],
    availabilityNote: "Weekday evenings",
  },
  {
    id: "c4",
    userId: "u-coach-4",
    name: "John Martinez",
    email: "john@athlink.app",
    sport: "野球",
    specialties: ["バッティング", "スカウト対策"],
    bio: "MLBマイナーリーグ経験。米国式トレーニングと日本の野球文化を橋渡し。英語・スペイン語レッスン対応。",
    location: "Los Angeles, CA",
    city: "Los Angeles",
    prefecture: "Los Angeles",
    experienceYears: 15,
    pricePerHour: 140,
    rating: 5.0,
    reviewCount: 19,
    verified: true,
    formats: ["in_person", "online"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=John",
    coverGradient: "from-blue-700 to-slate-800",
    career: ["元MLBマイナー", "USC野球プログラム指導", "スカウトアドバイザー"],
    languages: ["English", "Spanish", "Japanese"],
    availabilityNote: "Book 1 week ahead",
  },
  {
    id: "c5",
    userId: "u-coach-5",
    name: "Naoki Sato",
    email: "sato@athlink.app",
    sport: "野球",
    specialties: ["メンタル", "バッティング"],
    bio: "スポーツ心理士資格を持つコーチ。緊張しやすい選手のメンタル強化と試合でのパフォーマンス向上を支援します。",
    location: "San Francisco Bay Area, CA",
    city: "San Jose",
    prefecture: "San Francisco Bay Area",
    experienceYears: 10,
    pricePerHour: 80,
    rating: 4.6,
    reviewCount: 31,
    verified: false,
    formats: ["online"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sato",
    coverGradient: "from-violet-600 to-purple-800",
    career: ["スポーツ心理士", "高校野球メンタルコーチ", "プロ選手サポート経験"],
    languages: ["Japanese", "English", "Mandarin"],
    availabilityNote: "Online · evenings available",
  },
  {
    id: "c6",
    userId: "u-coach-6",
    name: "Ayumi Nakamura",
    email: "nakamura@athlink.app",
    sport: "ソフトボール",
    specialties: ["ピッチング", "守備"],
    bio: "ソフトボール日本代表経験。ウィンドミル投法の基礎から実戦までの一貫指導。",
    location: "Sacramento, CA",
    city: "Sacramento",
    prefecture: "Sacramento",
    experienceYears: 11,
    pricePerHour: 90,
    rating: 4.9,
    reviewCount: 27,
    verified: true,
    formats: ["in_person", "online"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Nakamura",
    coverGradient: "from-amber-500 to-red-600",
    career: ["ソフトボール日本代表", "大学ソフトボール監督", "ジュニア育成コーチ"],
    languages: ["Japanese", "English"],
    availabilityNote: "Weekends in-person · weekday online",
  },
  {
    id: "c7",
    userId: "u-coach-7",
    name: "Diego Alvarez",
    email: "diego@athlink.app",
    sport: "野球",
    specialties: ["フィジカル", "走塁"],
    bio: "元陸上部出身のストレングスコーチ。野球特化のスピード・パワー強化プログラムを提供。スペイン語対応。",
    location: "Inland Empire, CA",
    city: "Riverside",
    prefecture: "Inland Empire",
    experienceYears: 6,
    pricePerHour: 65,
    rating: 4.5,
    reviewCount: 14,
    verified: true,
    formats: ["in_person"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Diego",
    coverGradient: "from-lime-600 to-green-800",
    career: ["NSCA-CSCS", "プロ球団S&Cアシスタント", "高校陸上部コーチ"],
    languages: ["Spanish", "English"],
    availabilityNote: "Weekday afternoons & Saturdays",
  },
  {
    id: "c8",
    userId: "u-coach-8",
    name: "Ren Takahashi",
    email: "takahashi@athlink.app",
    sport: "野球",
    specialties: ["バッティング", "守備", "スカウト対策"],
    bio: "甲子園出場経験あり。中学〜高校生の進路相談と技術指導をセットでサポートします。",
    location: "Central Valley, CA",
    city: "Fresno",
    prefecture: "Central Valley",
    experienceYears: 8,
    pricePerHour: 75,
    rating: 4.8,
    reviewCount: 41,
    verified: true,
    formats: ["in_person", "online"],
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Takahashi",
    coverGradient: "from-cyan-600 to-blue-800",
    career: ["甲子園出場", "大学野球主将", "独立系プライベートコーチ"],
    languages: ["Japanese", "English", "Korean"],
    availabilityNote: "Flexible by booking",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    coachId: "c1",
    authorName: "Parent · K",
    rating: 5,
    comment:
      "息子のスイングが1ヶ月で見違えるほど変わりました。説明が分かりやすく、保護者にも丁寧にフィードバックしてくれます。",
    date: "2026-06-12",
    athleteLevel: "Grade 5",
  },
  {
    id: "r2",
    coachId: "c1",
    authorName: "Athlete · Y",
    rating: 5,
    comment: "オンラインでも動画解析が丁寧で、次の練習ですぐ試せるポイントがもらえます。",
    date: "2026-05-28",
    athleteLevel: "HS Sophomore",
  },
  {
    id: "r3",
    coachId: "c2",
    authorName: "Athlete · A",
    rating: 5,
    comment: "球速が上がりました。ケガ予防のケアも教えてもらえて安心です。",
    date: "2026-06-01",
    athleteLevel: "8th grade",
  },
  {
    id: "r4",
    coachId: "c4",
    authorName: "Parent · M",
    rating: 5,
    comment:
      "アメリカの考え方と日本の練習をうまく組み合わせてくれて、息子のモチベーションが上がりました。",
    date: "2026-04-18",
    athleteLevel: "HS Freshman",
  },
  {
    id: "r5",
    coachId: "c6",
    authorName: "Athlete · S",
    rating: 5,
    comment: "ウィンドミルのフォームを基礎から直してもらい、コントロールが安定しました。",
    date: "2026-05-05",
    athleteLevel: "HS Sophomore",
  },
  {
    id: "r6",
    coachId: "c8",
    authorName: "Parent · T",
    rating: 4,
    comment: "進路相談も一緒にしてくれて心強かったです。技術面も着実に伸びています。",
    date: "2026-06-20",
    athleteLevel: "8th grade",
  },
];

function buildSlots(): TimeSlot[] {
  const slots: TimeSlot[] = [];
  const times = [
    ["09:00", "10:00"],
    ["10:30", "11:30"],
    ["13:00", "14:00"],
    ["15:00", "16:00"],
    ["17:00", "18:00"],
    ["19:00", "20:00"],
  ];
  const start = new Date("2026-07-28T00:00:00");
  coaches.forEach((coach, ci) => {
    for (let d = 0; d < 14; d++) {
      const date = new Date(start);
      date.setDate(start.getDate() + d);
      const dateStr = date.toISOString().slice(0, 10);
      times.forEach(([startTime, endTime], ti) => {
        slots.push({
          id: `${coach.id}-${dateStr}-${startTime}`,
          coachId: coach.id,
          date: dateStr,
          startTime,
          endTime,
          available: (ci + d + ti) % 3 !== 0,
        });
      });
    }
  });
  return slots;
}

export const timeSlots = buildSlots();

export const demoBookings: Booking[] = [
  {
    id: "b1",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-1",
    athleteName: "Ethan Park",
    date: "2026-07-30",
    startTime: "17:00",
    endTime: "18:00",
    format: "in_person",
    packageType: "single",
    price: 95,
    status: "confirmed",
    note: "バッティングフォームの確認をお願いします",
    createdAt: "2026-07-20T10:00:00",
  },
  {
    id: "b2",
    coachId: "c5",
    coachName: "Naoki Sato",
    athleteId: "u-athlete-1",
    athleteName: "Demo Athlete",
    date: "2026-08-02",
    startTime: "19:00",
    endTime: "20:00",
    format: "online",
    packageType: "single",
    price: 80,
    status: "pending",
    createdAt: "2026-07-25T14:30:00",
  },
  {
    id: "b3",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-2",
    athleteName: "Sofia Reyes",
    date: "2026-07-29",
    startTime: "16:00",
    endTime: "17:00",
    format: "in_person",
    packageType: "single",
    price: 95,
    status: "pending",
    note: "QR scan · pitching session",
    createdAt: "2026-07-28T09:00:00",
  },
  {
    id: "b4",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-3",
    athleteName: "Kenji Nakamura",
    date: "2026-07-31",
    startTime: "18:00",
    endTime: "19:00",
    format: "in_person",
    packageType: "pack",
    price: 428,
    status: "pending",
    createdAt: "2026-07-27T11:20:00",
  },
  {
    id: "b5",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-4",
    athleteName: "Maya Chen",
    date: "2026-08-01",
    startTime: "10:00",
    endTime: "11:00",
    format: "in_person",
    packageType: "single",
    price: 95,
    status: "confirmed",
    createdAt: "2026-07-26T16:00:00",
  },
  {
    id: "b6",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-2",
    athleteName: "Sofia Reyes",
    date: "2026-08-05",
    startTime: "17:00",
    endTime: "18:00",
    format: "online",
    packageType: "single",
    price: 95,
    status: "confirmed",
    createdAt: "2026-07-28T12:00:00",
  },
  {
    id: "b7",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-5",
    athleteName: "Liam Ortiz",
    date: "2026-08-08",
    startTime: "09:00",
    endTime: "10:00",
    format: "in_person",
    packageType: "single",
    price: 95,
    status: "pending",
    createdAt: "2026-07-29T08:00:00",
  },
];

export const messageThreads: MessageThread[] = [
  {
    id: "t1",
    coachId: "c1",
    coachName: "Shota Tanaka",
    athleteId: "u-athlete-1",
    athleteName: "あなた",
    lastMessage: "次回はスイング動画を持ってきてください！",
    updatedAt: "2026-07-26T18:20:00",
    unread: 1,
  },
  {
    id: "t2",
    coachId: "c2",
    coachName: "Misaki Suzuki",
    athleteId: "u-athlete-1",
    athleteName: "あなた",
    lastMessage: "体験レッスンのご予約、ありがとうございます。",
    updatedAt: "2026-07-24T09:10:00",
    unread: 0,
  },
];

export const messages: Message[] = [
  {
    id: "m1",
    threadId: "t1",
    senderId: "u-athlete-1",
    senderName: "あなた",
    body: "田中コーチ、先日はありがとうございました。次回もよろしくお願いします。",
    createdAt: "2026-07-26T17:50:00",
  },
  {
    id: "m2",
    threadId: "t1",
    senderId: "u-coach-1",
    senderName: "Shota Tanaka",
    body: "こちらこそ！次回はスイング動画を持ってきてください！",
    createdAt: "2026-07-26T18:20:00",
  },
  {
    id: "m3",
    threadId: "t2",
    senderId: "u-coach-2",
    senderName: "Misaki Suzuki",
    body: "体験レッスンのご予約、ありがとうございます。当日は動きやすい服装でお越しください。",
    createdAt: "2026-07-24T09:10:00",
  },
];

export function getCoachById(id: string) {
  return coaches.find((c) => c.id === id);
}

export function getReviewsByCoach(coachId: string) {
  return reviews.filter((r) => r.coachId === coachId);
}

export function getSlotsByCoach(coachId: string) {
  return timeSlots.filter((s) => s.coachId === coachId && s.available);
}
