import type { AthletePublicProfile, SocialPost } from "@/types";

export const athleteProfiles: AthletePublicProfile[] = [
  {
    id: "a1",
    userId: "u-athlete-1",
    name: "Ethan Park",
    email: "ethan.park@athlink.app",
    school: "Westside High School",
    classYear: "2028",
    height: "5'10\"",
    weight: "165 lb",
    position: "OF",
    batsThrows: "R/R",
    location: "Los Angeles, CA",
    bio: "Looking for private hitting work this offseason. Competitive travel ball.",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Ethan",
    seasonStats: {
      seasonLabel: "2026 HS season",
      avg: ".342",
      obp: ".421",
      slg: ".518",
      hr: 4,
      rbi: 28,
      games: 32,
    },
    lookingForCoach: true,
    openToScouts: true,
  },
  {
    id: "a2",
    userId: "u-athlete-2",
    name: "Sofia Reyes",
    email: "sofia.reyes@athlink.app",
    school: "Coastal Prep Academy",
    classYear: "2027",
    height: "5'7\"",
    weight: "140 lb",
    position: "P",
    batsThrows: "R/R",
    location: "Orange County, CA",
    bio: "RHP working on FB command and changeup. Open to pitching coaches.",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia",
    seasonStats: {
      seasonLabel: "2026 HS season",
      era: "1.84",
      wins: 8,
      strikeouts: 92,
      games: 14,
    },
    lookingForCoach: true,
    openToScouts: true,
  },
  {
    id: "a3",
    userId: "u-athlete-3",
    name: "Kenji Nakamura",
    email: "kenji.n@athlink.app",
    school: "Pacific Youth Baseball",
    classYear: "2031",
    height: "5'2\"",
    weight: "105 lb",
    position: "SS",
    batsThrows: "R/R",
    location: "San Diego, CA",
    bio: "11U shortstop. Sharing defensive footwork and tee work.",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Kenji",
    seasonStats: {
      seasonLabel: "2026 travel season",
      avg: ".389",
      obp: ".455",
      games: 40,
    },
    lookingForCoach: true,
    openToScouts: false,
  },
  {
    id: "a4",
    userId: "u-athlete-4",
    name: "Maya Chen",
    email: "maya.chen@athlink.app",
    school: "Bayview High School",
    classYear: "2026",
    height: "5'6\"",
    weight: "145 lb",
    position: "C",
    batsThrows: "S/R",
    location: "San Jose, CA",
    bio: "Senior catcher. Pop time & framing clips for college coaches / scouts.",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Maya",
    seasonStats: {
      seasonLabel: "2026 HS season",
      avg: ".311",
      obp: ".398",
      slg: ".467",
      hr: 3,
      rbi: 31,
      games: 30,
    },
    lookingForCoach: false,
    openToScouts: true,
  },
];

/** Demo short clips (public sample MP4s) */
const V = {
  a: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  b: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  c: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  d: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
};

export const seedSocialPosts: SocialPost[] = [
  {
    id: "p1",
    athleteId: "a1",
    athleteName: "Ethan Park",
    school: "Westside High School",
    position: "OF",
    classYear: "2028",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Ethan",
    type: "form",
    caption: "Side view — working on attack angle vs outside FB. Feedback welcome.",
    videoUrl: V.a,
    posterUrl: "https://images.unsplash.com/photo-1566577739112-5180d4bf694c?w=800&q=80",
    statsNote: "Season AVG .342",
    createdAt: "2026-07-28T16:20:00",
    likes: 24,
  },
  {
    id: "p2",
    athleteId: "a2",
    athleteName: "Sofia Reyes",
    school: "Coastal Prep Academy",
    position: "P",
    classYear: "2027",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia",
    type: "practice",
    caption: "Bullpen — FB command glove side. Looking for a pitching coach in OC.",
    videoUrl: V.b,
    posterUrl: "https://images.unsplash.com/photo-1508344928928-7528d0e3b3a5?w=800&q=80",
    statsNote: "ERA 1.84 · 92 K",
    createdAt: "2026-07-27T11:05:00",
    likes: 41,
  },
  {
    id: "p3",
    athleteId: "a4",
    athleteName: "Maya Chen",
    school: "Bayview High School",
    position: "C",
    classYear: "2026",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Maya",
    type: "game",
    caption: "Game throwdown — pop ~2.05. Open to college coaches & scouts.",
    videoUrl: V.c,
    posterUrl: "https://images.unsplash.com/photo-1471295253337-3ceaaedca402?w=800&q=80",
    statsNote: "2026: .311 / .398 / .467",
    createdAt: "2026-07-26T19:40:00",
    likes: 67,
  },
  {
    id: "p4",
    athleteId: "a3",
    athleteName: "Kenji Nakamura",
    school: "Pacific Youth Baseball",
    position: "SS",
    classYear: "2031",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Kenji",
    type: "training",
    caption: "Self-training: funnel & backhand footwork at the park.",
    videoUrl: V.d,
    posterUrl: "https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?w=800&q=80",
    createdAt: "2026-07-25T09:15:00",
    likes: 18,
  },
  {
    id: "p5",
    athleteId: "a1",
    athleteName: "Ethan Park",
    school: "Westside High School",
    position: "OF",
    classYear: "2028",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Ethan",
    type: "highlight",
    caption: "Game triple to the gap — sharing for coaches reviewing my profile.",
    videoUrl: V.b,
    posterUrl: "https://images.unsplash.com/photo-1529768167804-613441e17f4f?w=800&q=80",
    statsNote: "4 HR · 28 RBI",
    createdAt: "2026-07-24T21:00:00",
    likes: 33,
  },
];

export function getAthleteById(id: string) {
  return athleteProfiles.find((a) => a.id === id);
}

export function getAthleteByUserId(userId: string) {
  return athleteProfiles.find((a) => a.userId === userId);
}

export function getPostsByAthlete(athleteId: string, posts: SocialPost[]) {
  return posts.filter((p) => p.athleteId === athleteId);
}
