window.ATLAS_DATA = {
  attribution:
    "Basemap © Esri · Corridors are schematic public-geography diagrams, not surveyed as-builts. Supply shares are ranges, not single-year truth.",
  palette: {
    colorado: { line: "#c27803", glow: "#fcd34d", fill: "#92400e" },
    sierra: { line: "#0f766e", glow: "#2dd4bf", fill: "#115e59" },
    swp: { line: "#2563eb", glow: "#93c5fd", fill: "#1e40af" },
    groundwater: { line: "#64748b", glow: "#cbd5e1", fill: "#475569" },
    recycled: { line: "#059669", glow: "#6ee7b7", fill: "#047857" },
  },
  entry: {
    center: [-118.25, 34.05],
    zoom: 9.6,
    bearing: 0,
    pitch: 28,
  },
  overview: {
    center: [-117.8, 35.2],
    zoom: 5.85,
    bearing: -6,
    pitch: 18,
  },
  routes: {
    sierra: {
      id: "sierra",
      name: { en: "Los Angeles Aqueduct", ja: "ロサンゼルス水道橋" },
      coordinates: [
        [-119.012, 38.007],
        [-118.98, 37.78],
        [-118.74, 37.64],
        [-118.395, 37.363],
        [-118.2, 36.803],
        [-117.95, 36.433],
        [-117.958, 36.137],
        [-117.99, 35.72],
        [-118.17, 35.05],
        [-118.28, 34.72],
        [-118.4, 34.55],
        [-118.498, 34.322],
        [-118.44, 34.16],
        [-118.25, 34.053],
      ],
    },
    swp: {
      id: "swp",
      name: { en: "State Water Project", ja: "州水道プロジェクト" },
      coordinates: [
        [-121.485, 39.538],
        [-121.63, 39.2],
        [-121.56, 38.58],
        [-121.5, 38.06],
        [-121.62, 37.8],
        [-121.075, 37.066],
        [-120.38, 36.0],
        [-119.55, 35.45],
        [-118.82, 35.04],
        [-118.61, 34.587],
        [-118.48, 34.28],
        [-118.25, 34.053],
      ],
    },
    colorado: {
      id: "colorado",
      name: { en: "Colorado River Aqueduct", ja: "コロラド川水道橋" },
      coordinates: [
        [-114.139, 34.296],
        [-114.53, 34.16],
        [-115.12, 34.15],
        [-115.49, 33.81],
        [-115.9, 33.7],
        [-116.55, 33.87],
        [-116.95, 33.88],
        [-117.454, 33.851],
        [-117.85, 34.02],
        [-118.25, 34.053],
      ],
    },
  },
  places: [
    { id: "la", name: { en: "Los Angeles", ja: "ロサンゼルス" }, lng: -118.2437, lat: 34.0522, kind: "city" },
    { id: "owens", name: { en: "Owens Valley", ja: "オーウェンズ谷" }, lng: -118.2, lat: 36.8, kind: "source", source: "sierra" },
    { id: "mono", name: { en: "Mono Lake", ja: "モノ湖" }, lng: -119.012, lat: 38.007, kind: "source", source: "sierra" },
    { id: "oroville", name: { en: "Lake Oroville", ja: "オロビル湖" }, lng: -121.485, lat: 39.538, kind: "source", source: "swp" },
    { id: "delta", name: { en: "Delta", ja: "デルタ" }, lng: -121.5, lat: 38.06, kind: "node", source: "swp" },
    { id: "tehachapi", name: { en: "Edmonston / Tehachapi", ja: "エドモンストン／テハチャピ" }, lng: -118.82, lat: 35.04, kind: "energy", source: "swp" },
    { id: "parker", name: { en: "Parker Dam", ja: "パーカーダム" }, lng: -114.139, lat: 34.296, kind: "source", source: "colorado" },
    { id: "mathews", name: { en: "Lake Mathews", ja: "マシューズ湖" }, lng: -117.454, lat: 33.851, kind: "node", source: "colorado" },
    { id: "castaic", name: { en: "Castaic Lake", ja: "カスタイック湖" }, lng: -118.61, lat: 34.587, kind: "node", source: "swp" },
    { id: "sfbasin", name: { en: "San Fernando Basin", ja: "サンフェルナンド盆地" }, lng: -118.44, lat: 34.22, kind: "local", source: "groundwater" },
    { id: "central", name: { en: "Central Basin", ja: "セントラル盆地" }, lng: -118.15, lat: 33.98, kind: "local", source: "groundwater" },
  ],
  sources: [
    {
      id: "colorado",
      color: "colorado",
      title: { en: "Colorado River", ja: "コロラド川" },
      share: { en: "Major MWD import · share varies by year", ja: "MWD輸入の主要源 · 年により構成比は変動" },
      volume: { en: "Basin-shared allocation via CRA", ja: "コロラド川水道橋経由の流域共有割当" },
      note: {
        en: "1922 Compact-era assumptions overstate reliable flow; Mead/Powell stress travels into Southern California (Barnett & Pierce 2008; USBR).",
        ja: "1922年協定期の流量想定は信頼性を過大評価しやすい。ミード／パウエルのストレスは南カリフォルニアへ届く（Barnett & Pierce 2008; USBR）。",
      },
      fly: { center: [-115.2, 34.0], zoom: 6.8, bearing: 18, pitch: 36 },
    },
    {
      id: "sierra",
      color: "sierra",
      title: { en: "Eastern Sierra / Owens", ja: "東部シエラ／オーウェンズ" },
      share: { en: "LAA ≈ 10–50% of city supply (snowpack-dependent)", ja: "LAA ≈ 市供給の10–50%（積雪依存）" },
      volume: { en: "~230,000 AF/yr recent · ~half retained for Owens/Mono", ja: "近年約23万AF/年 · 約半分はオーウェンズ／モノに残留" },
      note: {
        en: "When snowpack falls, LAA deliveries drop and MWD purchases rise — vulnerability maps onto distant imports (LADWP UWMP / Briefing Book).",
        ja: "積雪が減るとLAAが落ち、MWD購入が増える。脆弱性が遠い輸入に載る（LADWP UWMP / Briefing Book）。",
      },
      fly: { center: [-118.35, 36.8], zoom: 7.2, bearing: -16, pitch: 42 },
    },
    {
      id: "swp",
      color: "swp",
      title: { en: "State Water Project", ja: "州水道プロジェクト" },
      share: { en: "Northern CA → Delta → Tehachapi lift → SoCal", ja: "北カリフォルニア → デルタ → テハチャピ揚水 → 南カリフォルニア" },
      volume: { en: "Allocation swings with hydrology & Delta constraints", ja: "水文とデルタ制約で割当が大きく振れる" },
      note: {
        en: "Edmonston / Tehachapi lift couples water reliability to energy systems — pumping stoppage is a supply risk.",
        ja: "エドモンストン／テハチャピ揚水は水の信頼性をエネルギー系と結合する — 揚水停止は供給リスク。",
      },
      fly: { center: [-120.2, 36.5], zoom: 6.2, bearing: -8, pitch: 28 },
    },
    {
      id: "groundwater",
      color: "groundwater",
      title: { en: "Local groundwater", ja: "地元地下水" },
      share: { en: "Local buffer · basin cleanup still matters", ja: "地元バッファ · 盆地浄化が引き続き重要" },
      volume: { en: "San Fernando & coastal basins (schematic)", ja: "サンフェルナンド＆沿岸盆地（模式）" },
      note: {
        en: "Local supply is not infinite — contamination, recharge, and rights shape how much can be used in dry years.",
        ja: "地元供給は無限ではない。汚染・涵養・権利が乾燥年の利用可能量を規定する。",
      },
      fly: { center: [-118.3, 34.12], zoom: 10.1, bearing: 0, pitch: 30 },
    },
    {
      id: "recycled",
      color: "recycled",
      title: { en: "Recycled & stormwater", ja: "再生水・雨水" },
      share: { en: "Growing local portfolio · resilience lever", ja: "拡大中の地元ポートフォリオ · レジリエンスのてこ" },
      volume: { en: "Reuse + capture reduce import pressure over time", ja: "再利用＋貯留が長期で輸入圧力を緩和" },
      note: {
        en: "Policy simulator treats recycled expansion as one response option under growth and drought stress — not a silver bullet.",
        ja: "政策シミュレータでは再生水拡大を、成長・旱魃ストレスへの選択肢の一つとして扱う — 銀の弾丸ではない。",
      },
      fly: { center: [-118.28, 33.95], zoom: 10.4, bearing: 4, pitch: 26 },
    },
  ],
  process: [
    { id: "snow", en: "Snowpack", ja: "積雪" },
    { id: "reservoir", en: "Reservoir", ja: "貯水" },
    { id: "aqueduct", en: "Aqueduct", ja: "水道橋" },
    { id: "treatment", en: "Treatment", ja: "浄水" },
    { id: "distribution", en: "Distribution", ja: "配水" },
    { id: "tap", en: "Tap", ja: "蛇口" },
  ],
  infrastructure: [
    {
      id: "cra",
      source: "colorado",
      title: { en: "Colorado River Aqueduct", ja: "コロラド川水道橋" },
      facts: {
        en: ["~242 miles", "5 pumping plants", "Desert crossing", "MWD asset"],
        ja: ["約242マイル", "揚水場5か所", "砂漠横断", "MWD資産"],
      },
      body: {
        en: "Moves Colorado River water across the Mojave into Southern California’s wholesale system. Length and lift make energy a first-class variable.",
        ja: "コロラド川の水をモハベ横断で南カリフォルニアの卸供給へ運ぶ。延長と揚程によりエネルギーは第一級の変数になる。",
      },
      fly: { center: [-116.2, 33.95], zoom: 7.4, bearing: 20, pitch: 38 },
    },
    {
      id: "laa",
      source: "sierra",
      title: { en: "Los Angeles Aqueduct", ja: "ロサンゼルス水道橋" },
      facts: {
        en: [">200 miles", "Eastern Sierra source", "Gravity-dominant", "LADWP"],
        ja: ["200マイル超", "東部シエラ水源", "重力利用が中心", "LADWP"],
      },
      body: {
        en: "Owens / Mono snowmelt corridor. Environmental obligations retain roughly half of historically exported Eastern Sierra water.",
        ja: "オーウェンズ／モノの融雪回廊。歴史的に輸出していた東部シエラ水の約半分は環境義務で現地に残る。",
      },
      fly: { center: [-118.2, 35.6], zoom: 7.0, bearing: -12, pitch: 40 },
    },
    {
      id: "edmonston",
      source: "swp",
      title: { en: "Edmonston Pumping Plant", ja: "エドモンストン揚水場" },
      facts: {
        en: ["Tehachapi lift", "Highest SWP lift", "Energy-critical", "DWR / SWP"],
        ja: ["テハチャピ揚水", "SWP最大級の揚程", "エネルギー臨界", "DWR / SWP"],
      },
      body: {
        en: "Northern water must be lifted over the Tehachapis. An outage here is not only an energy event — it is a Southern California supply event.",
        ja: "北部の水はテハチャピを越えなければならない。ここでの停止はエネルギー事象であると同時に、南カリフォルニアの供給事象である。",
      },
      fly: { center: [-118.82, 35.04], zoom: 9.2, bearing: -4, pitch: 45 },
    },
  ],
  climateSeries: [
    { year: 1980, snow: 108 },
    { year: 1985, snow: 92 },
    { year: 1990, snow: 68 },
    { year: 1995, snow: 118 },
    { year: 2000, snow: 95 },
    { year: 2005, snow: 110 },
    { year: 2010, snow: 88 },
    { year: 2015, snow: 42 },
    { year: 2020, snow: 71 },
    { year: 2023, snow: 142 },
    { year: 2025, snow: 78 },
  ],
  droughtPath: [
    {
      year: 2012,
      en: "Multi-year drought begins to tighten Sierra & SWP allocations.",
      ja: "複数年旱魃がシエラとSWP割当を締め始める。",
    },
    {
      year: 2015,
      en: "Deep snowpack deficit; LAA share drops; MWD dependence rises.",
      ja: "積雪が大きく不足。LAA比率低下、MWD依存上昇。",
    },
    {
      year: 2022,
      en: "Colorado River shortage operations intensify basin-wide stress.",
      ja: "コロラド川不足運用が流域全体のストレスを強める。",
    },
    {
      year: 2035,
      en: "Scenario horizon — compare policies under shared assumptions, not a single forecast.",
      ja: "シナリオ地平 — 単一予測ではなく、共通前提の下で政策を比較する。",
    },
  ],
  why: [
    {
      id: "history",
      title: { en: "History", ja: "歴史" },
      body: {
        en: "Metropolitan growth depended on interbasin transfer — moving water across mountains and deserts (Hundley 2001; Kahrl 1982). The tap is local; production is regional.",
        ja: "大都市成長は流域間導水に依存した — 山と砂漠を越えて水を動かす（Hundley 2001; Kahrl 1982）。蛇口は地元。生産は広域。",
      },
    },
    {
      id: "policy",
      title: { en: "Policy & law", ja: "政策と法" },
      body: {
        en: "Colorado River Compact allocations, Delta constraints, and Owens/Mono environmental obligations jointly structure what can arrive at the coastal plain.",
        ja: "コロラド川協定の割当、デルタ制約、オーウェンズ／モノの環境義務が、海岸平野へ届く量を共同で規定する。",
      },
    },
    {
      id: "nexus",
      title: { en: "Energy–water nexus", ja: "エネルギーと水" },
      body: {
        en: "Long aqueducts require lift. Outage and power cost are water-security variables — not side notes to hydrology.",
        ja: "長距離水道は揚水を要する。停電と電力コストは水安全保障の変数であり、水文の脇役ではない。",
      },
    },
    {
      id: "literacy",
      title: { en: "Public literacy", ja: "公開リテラシー" },
      body: {
        en: "Agency plans document mix and limits. Few public tools show cascading spatial risk without false precision. That is this Atlas’s design gap.",
        ja: "機関計画は構成と制約を記録する。偽の精確さなしに連鎖する空間リスクを見せる公開ツールは少ない。それがこのAtlasの設計ギャップ。",
      },
    },
  ],
  citations: [
    "LADWP Urban Water Management Plan (2020) & Briefing Book (2022–23)",
    "Hundley, N. (2001). The Great Thirst.",
    "Kahrl, W. (1982). Water and Power.",
    "MacDonald, G. (2010). Water, climate change, and sustainability in the Southwest.",
    "Barnett, T. & Pierce, D. (2008). When will Lake Mead go dry?",
    "Gleick, P. (2010). Roadmap for sustainable water resources in southwestern North America.",
    "U.S. Bureau of Reclamation — Colorado River shortage operations",
  ],
};
